version: "3.8"

services:
  nginx:
    container_name: name-nginx
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./code:/code
      - ./ssl:/ssl
      - ./nginx_conf/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx_conf/nginx.conf:/etc/nginx/nginx.conf
      - ./logs/nginx/:/var/log/nginx/
    environment:
      TZ: Asia/Jakarta
    links:
      - php
    restart: always

  php:
    container_name: name-php
    build:
      context: .
      dockerfile: Dockerfile-php7.4-fpm-alpine
    image: php:7.4-fpm-alpine
    volumes:
      - ./code:/code
      - ./php_conf/php.ini:/usr/local/etc/php/php.ini
    environment:
      TZ: Asia/Jakarta
    restart: always
